# Site settings
title: Andy Kamath
email: andy@hackgician.net
description: > # this means to ignore newlines until "baseurl:"
  I'm a sophomore and a tech enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andykamath.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
