# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy Kamath
email: your-email@domain.com
description: Computer Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
img: "https://scontent-atl3-1.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/12391410_432159773656269_5190042455339779781_n.jpg?oh=f01e802acbb5e6c808bdbcd3b1bb5120&oe=572E307A"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
