# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy Kamath
email: your-email@domain.com
description: Computer Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
img: "https://avatars3.githubusercontent.com/u/7597423?v=3&s=460"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
